<x-guest-layout>
    <section class="mx-auto grid min-h-[min(760px,calc(100dvh-76px))] max-w-7xl items-center gap-12 px-4 py-16 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:px-10 lg:py-24">
        <div>
            <p class="mb-5 text-xs font-bold uppercase tracking-[0.28em] text-moss">Community preorder marketplace</p>
            <h1 class="max-w-4xl font-display text-6xl font-semibold leading-[.92] tracking-[-0.07em] sm:text-8xl">Good ideas deserve a waiting list.</h1>
            <p class="mt-8 max-w-xl text-lg leading-8 text-ink/65">Preshop helps independent makers test an idea, gather real orders, and build the next thing with their community.</p>
            <div class="mt-9 flex flex-wrap items-center gap-4"><a href="{{ route('customer.shop') }}" class="rounded-full bg-accent px-6 py-3 font-bold text-white hover:-translate-y-0.5 hover:bg-accent-dark">Browse live campaigns <span class="ml-2">↗</span></a><a href="{{ route('register') }}" class="font-semibold text-ink underline decoration-ink/20 underline-offset-8 hover:text-accent">Start making</a></div>
            <div class="mt-14 flex gap-10 border-t border-ink/15 pt-5 text-sm"><div><p class="font-display text-2xl font-semibold">01</p><p class="mt-1 text-ink/55">Share the idea</p></div><div><p class="font-display text-2xl font-semibold">02</p><p class="mt-1 text-ink/55">Gather support</p></div><div><p class="font-display text-2xl font-semibold">03</p><p class="mt-1 text-ink/55">Make it real</p></div></div>
        </div>
        <div class="relative mx-auto w-full max-w-lg lg:ml-auto">
            <div class="surface-shadow relative rotate-2 overflow-hidden rounded-[2rem] bg-ink p-3"><div class="overflow-hidden rounded-[1.5rem] bg-accent"><img src="{{ asset('asset/checkout.webp') }}" alt="A maker's product ready for preorder" class="h-[28rem] w-full object-cover mix-blend-multiply opacity-80 sm:h-[34rem]"><div class="absolute inset-x-8 bottom-8 rounded-2xl bg-paper p-5"><p class="text-xs font-bold uppercase tracking-[0.2em] text-moss">Now collecting support</p><p class="mt-2 font-display text-2xl font-semibold">The things we make together</p><div class="mt-4 flex items-center justify-between text-sm"><span class="text-ink/55">64 backers</span><span class="font-bold text-accent">RM 48.00</span></div></div></div></div><span class="absolute -right-5 -top-5 rotate-12 rounded-full bg-moss px-4 py-3 text-xs font-bold text-paper shadow-lg">made by people</span>
        </div>
    </section>
    <section class="bg-ink px-4 py-16 text-paper sm:px-6 lg:px-10"><div class="mx-auto grid max-w-7xl gap-8 md:grid-cols-3"><div class="md:col-span-2"><p class="text-xs font-bold uppercase tracking-[0.28em] text-accent">A small place for big maybes</p><h2 class="mt-4 max-w-2xl font-display text-4xl font-semibold tracking-tight sm:text-5xl">From first sketch to first shipment, keep the signal close.</h2></div><p class="self-end max-w-sm leading-7 text-paper/60">No complicated storefront. No guesswork. Just a clear campaign page, honest demand, and the people who want to see it happen.</p></div></section>
</x-guest-layout>
