<div class="min-h-[100dvh] bg-paper">
    <div class="mx-auto max-w-7xl space-y-8 px-4 py-10 sm:px-6 lg:px-10">
        <div><p class="text-xs font-bold uppercase tracking-[0.28em] text-moss">Money movement</p><h1 class="mt-3 font-display text-4xl font-bold tracking-[-0.04em]">Payouts</h1><p class="mt-2 text-sm text-ink/55">Review withdrawal requests and inspect the wallet ledger.</p></div>

        <section class="rounded-[2rem] bg-white p-6 shadow-[0_20px_60px_rgba(71,52,38,.07)] ring-1 ring-ink/5 sm:p-8">
            <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-[10px] font-bold uppercase tracking-[0.22em] text-accent">Action queue</p><h2 class="mt-2 font-display text-2xl font-bold">Pending withdrawals</h2></div><div class="flex gap-2"><label><span class="sr-only">Search pending withdrawals</span><input wire:model.live.debounce.300ms="searchWithdrawal" type="search" placeholder="Search maker" class="w-full rounded-xl border-0 bg-paper px-4 py-3 text-sm ring-1 ring-ink/10 focus:ring-2 focus:ring-accent sm:w-56"></label><select wire:model.live="withdrawalPerPage" aria-label="Pending withdrawal rows" class="rounded-xl border-0 bg-paper px-3 py-3 text-sm ring-1 ring-ink/10 focus:ring-2 focus:ring-accent"><option value="10">10</option><option value="25">25</option></select></div></div>
            <div class="mt-6 overflow-x-auto"><table class="min-w-[920px] w-full text-left text-sm"><thead class="border-b border-ink/10 text-[10px] uppercase tracking-[0.18em] text-ink/45"><tr><th class="pb-3 pr-4">Maker</th><th class="pb-3 pr-4">Bank</th><th class="pb-3 pr-4">Account</th><th class="pb-3 pr-4">Requested</th><th class="pb-3 pr-4">Amount</th><th class="pb-3 text-right">Action</th></tr></thead><tbody class="divide-y divide-ink/10">@forelse ($withdrawals as $withdrawal)<tr wire:key="withdrawal-{{ $withdrawal->id }}" wire:loading.class="opacity-50"><td class="py-4 pr-4"><p class="font-semibold">{{ $withdrawal->wallet->user->name }}</p><p class="mt-1 font-mono text-[11px] text-ink/40">Request #{{ $withdrawal->id }}</p></td><td class="py-4 pr-4 text-ink/60">{{ $withdrawal->wallet->bank_name ?: 'Not provided' }}</td><td class="py-4 pr-4 font-mono text-xs">•••• {{ substr($withdrawal->wallet->bank_account_number ?: '—', -4) }}</td><td class="py-4 pr-4 whitespace-nowrap text-xs text-ink/50">{{ $withdrawal->created_at->format('d M Y, g:i A') }}</td><td class="py-4 pr-4 font-mono font-bold tabular-nums">RM {{ number_format($withdrawal->withdrawn_amount / 100, 2) }}</td><td class="py-4 text-right"><div class="flex justify-end gap-2"><button type="button" wire:click="confirmWithdrawal({{ $withdrawal->id }}, 'reject')" class="rounded-full border border-accent/30 px-3 py-2 text-xs font-semibold text-accent-dark hover:bg-accent/10">Reject</button><button type="button" wire:click="confirmWithdrawal({{ $withdrawal->id }}, 'approve')" class="rounded-full bg-ink px-3 py-2 text-xs font-semibold text-paper hover:bg-moss">Approve</button></div></td></tr>@empty<tr><td colspan="6" class="py-10 text-center text-ink/50">No withdrawals are waiting for review.</td></tr>@endforelse</tbody></table></div>
            <div class="mt-4">{{ $withdrawals->links() }}</div>
        </section>

        <section class="grid gap-6 lg:grid-cols-2">
            <div class="rounded-[2rem] bg-white p-6 shadow-[0_20px_60px_rgba(71,52,38,.07)] ring-1 ring-ink/5 sm:p-8"><div class="flex items-end justify-between gap-4"><div><p class="text-[10px] font-bold uppercase tracking-[0.22em] text-moss">Wallets</p><h2 class="mt-2 font-display text-2xl font-bold">Balance pool</h2></div><input wire:model.live.debounce.300ms="searchWallet" type="search" aria-label="Search wallets" placeholder="Search maker" class="w-40 rounded-xl border-0 bg-paper px-3 py-2 text-xs ring-1 ring-ink/10 focus:ring-2 focus:ring-accent"></div><div class="mt-6 overflow-x-auto"><table class="min-w-[520px] w-full text-left text-sm"><thead class="border-b border-ink/10 text-[10px] uppercase tracking-[0.18em] text-ink/45"><tr><th class="pb-3 pr-4">Maker</th><th class="pb-3 pr-4">Earnings</th><th class="pb-3">Available</th></tr></thead><tbody class="divide-y divide-ink/10">@forelse ($wallets as $wallet)<tr wire:key="wallet-{{ $wallet->id }}"><td class="py-4 pr-4 font-semibold">{{ $wallet->user->name }}</td><td class="py-4 pr-4 font-mono tabular-nums">RM {{ number_format($wallet->earning / 100, 2) }}</td><td class="py-4 font-mono font-bold tabular-nums">RM {{ number_format($wallet->balance / 100, 2) }}</td></tr>@empty<tr><td colspan="3" class="py-8 text-center text-ink/50">No wallets found.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $wallets->links() }}</div></div>

            <div class="rounded-[2rem] bg-white p-6 shadow-[0_20px_60px_rgba(71,52,38,.07)] ring-1 ring-ink/5 sm:p-8"><div class="flex items-end justify-between gap-4"><div><p class="text-[10px] font-bold uppercase tracking-[0.22em] text-moss">Ledger</p><h2 class="mt-2 font-display text-2xl font-bold">Recent transactions</h2></div><input wire:model.live.debounce.300ms="searchTransaction" type="search" aria-label="Search transactions" placeholder="Search maker" class="w-40 rounded-xl border-0 bg-paper px-3 py-2 text-xs ring-1 ring-ink/10 focus:ring-2 focus:ring-accent"></div><div class="mt-6 overflow-x-auto"><table class="min-w-[560px] w-full text-left text-sm"><thead class="border-b border-ink/10 text-[10px] uppercase tracking-[0.18em] text-ink/45"><tr><th class="pb-3 pr-4">Maker</th><th class="pb-3 pr-4">Amount</th><th class="pb-3 pr-4">Status</th><th class="pb-3">Date</th></tr></thead><tbody class="divide-y divide-ink/10">@forelse ($transactions as $transaction)<tr wire:key="transaction-{{ $transaction->id }}"><td class="py-4 pr-4 font-semibold">{{ $transaction->wallet->user->name }}</td><td class="py-4 pr-4 font-mono font-bold tabular-nums">{{ $transaction->withdrawn_amount > 0 ? '-' : '+' }} RM {{ number_format(($transaction->withdrawn_amount ?: $transaction->credited_amount) / 100, 2) }}</td><td class="py-4 pr-4"><span class="rounded-full px-3 py-1 text-xs font-semibold {{ $transaction->status === \App\Models\Transaction::STATUS_PENDING ? 'bg-gold/15 text-deep-gold' : ($transaction->status === \App\Models\Transaction::STATUS_REJECTED ? 'bg-accent/10 text-accent-dark' : 'bg-moss/10 text-moss') }}">@switch($transaction->status) @case(1) Income @break @case(2) Approved @break @case(3) Pending @break @case(4) Rejected @break @default Unknown @endswitch</span></td><td class="py-4 whitespace-nowrap text-xs text-ink/50">{{ $transaction->created_at->format('d M Y') }}</td></tr>@empty<tr><td colspan="4" class="py-8 text-center text-ink/50">No transactions found.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $transactions->links() }}</div></div>
        </section>
    </div>

    <x-confirmation-modal wire:model="confirmModal" maxWidth="md">
        <x-slot name="title">{{ $selectedAction === 'reject' ? 'Reject withdrawal' : 'Approve withdrawal' }}</x-slot>
        <x-slot name="content">{{ $selectedAction === 'reject' ? 'Rejecting request #'.$selectedTransactionId.' returns the reserved amount to the maker wallet.' : 'Approve request #'.$selectedTransactionId.' only after the simulated transfer has been completed.' }}</x-slot>
        <x-slot name="footer"><x-secondary-button wire:click="$set('confirmModal', false)" wire:loading.attr="disabled">Cancel</x-secondary-button><x-button-custom type="button" class="ml-2" wire:click="executeWithdrawal" wire:loading.attr="disabled">{{ $selectedAction === 'reject' ? 'Reject request' : 'Approve request' }}</x-button-custom></x-slot>
    </x-confirmation-modal>
    <x-flash />
</div>
