@inject('carbon', 'Carbon\\Carbon')
@php
    $cover = $campaign->images->first();
    $backed = $campaign->orders->where('paid', true)->sum('quantity');
    $shippingEnabled = collect($campaign->shipping ?? [])->contains(fn ($value) => $value !== '' && $value !== null);
    $status = $campaign->end_date->isFuture() ? 'Active' : 'Closed';
@endphp

<x-slot name="header">
    <div class="flex items-center gap-3"><a href="{{ route('business.manage') }}" wire:navigate class="group flex size-8 items-center justify-center rounded-full bg-ink/5 text-ink/60 ring-1 ring-ink/10 transition-transform duration-700 ease-[cubic-bezier(.32,.72,0,1)] hover:-translate-x-1 hover:bg-accent hover:text-white"><svg viewBox="0 0 24 24" fill="none" class="size-4" aria-hidden="true"><path d="M19 12H5m6-7-7 7 7 7" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" /></svg></a><span class="text-sm font-semibold">Campaign studio</span></div>
</x-slot>

<section class="relative isolate overflow-hidden bg-paper">
    <div class="pointer-events-none absolute inset-x-0 top-0 -z-10 h-[34rem] bg-[radial-gradient(circle_at_6%_4%,rgba(105,115,91,.14),transparent_34%),radial-gradient(circle_at_96%_4%,rgba(232,111,81,.13),transparent_30%)]"></div>

    <div class="mx-auto max-w-7xl px-4 pb-20 pt-10 sm:px-6 sm:pt-14 lg:px-10 lg:pb-28">
        <div class="flex flex-col justify-between gap-8 lg:flex-row lg:items-end" data-animate="fade-up">
            <div class="max-w-3xl">
                <div class="flex flex-wrap items-center gap-3 text-[10px] font-semibold uppercase tracking-[0.2em] text-moss"><span class="inline-flex items-center gap-2 rounded-full bg-moss/10 px-3 py-1.5"><span class="size-1.5 rounded-full {{ $status === 'Active' ? 'bg-moss' : 'bg-accent' }}"></span>{{ $status }}</span><span>Campaign {{ str_pad($campaign->id, 4, '0', STR_PAD_LEFT) }}</span></div>
                <h1 class="mt-5 font-display text-5xl font-semibold leading-[.92] tracking-[-0.07em] text-ink sm:text-7xl">{{ $campaign->title }}</h1>
                <p class="mt-5 max-w-2xl text-base leading-7 text-ink/60">Shape the story, keep the details clear, and let the right people find this next run.</p>
            </div>
            <div class="flex flex-wrap gap-3 text-center"><div class="rounded-full bg-white/70 px-4 py-3 ring-1 ring-ink/10"><p class="text-[10px] uppercase tracking-[0.16em] text-ink/40">Backed</p><p class="mt-1 font-display text-xl font-semibold">{{ $backed }}</p></div><div class="rounded-full bg-white/70 px-4 py-3 ring-1 ring-ink/10"><p class="text-[10px] uppercase tracking-[0.16em] text-ink/40">Price</p><p class="mt-1 font-display text-xl font-semibold">{{ $campaign->currency }}{{ number_format($campaign->price / 100, 2) }}</p></div></div>
        </div>

        <div class="mt-12 grid gap-5 lg:grid-cols-[minmax(0,1.1fr)_minmax(20rem,.9fr)] lg:items-start lg:gap-8">
            <div class="rounded-[2rem] bg-ink/5 p-1.5 ring-1 ring-ink/10" data-animate="fade-up" data-delay="100">
                <div class="rounded-[calc(2rem-0.375rem)] bg-[#171412] p-5 text-paper shadow-[0_28px_80px_rgba(46,26,71,.14)] sm:p-7">
                    <div class="flex items-center justify-between gap-4"><div><p class="text-[10px] uppercase tracking-[0.22em] text-paper/45">Campaign assets</p><p class="mt-2 font-display text-2xl font-semibold tracking-[-0.04em]">The visual shelf</p></div><span class="text-xs text-paper/45">{{ $campaign->images->count() }}/5 assets</span></div>
                    <div class="mt-7 grid gap-3 sm:grid-cols-3">
                        @forelse ($campaign->images as $image)
                            <div class="group relative overflow-hidden rounded-[1.35rem] bg-paper/[.06] sm:first:col-span-2">
                                <img src="{{ asset('storage/campaign/' . $image->image) }}" alt="{{ $campaign->title }} campaign asset" class="aspect-[4/3] h-full w-full object-cover opacity-90 transition-transform duration-[1200ms] ease-[cubic-bezier(.32,.72,0,1)] group-hover:scale-105" />
                                <button type="button" wire:click="deleteImage({{ $image->id }})" aria-label="Remove campaign image" class="absolute right-3 top-3 flex size-8 items-center justify-center rounded-full bg-ink/70 text-paper/75 opacity-0 ring-1 ring-paper/15 transition-all duration-700 ease-[cubic-bezier(.32,.72,0,1)] group-hover:opacity-100 hover:bg-accent hover:text-white"><svg viewBox="0 0 24 24" fill="none" class="size-4" aria-hidden="true"><path d="m7 7 10 10M17 7 7 17" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" /></svg></button>
                            </div>
                        @empty
                            <div class="rounded-[1.35rem] bg-paper/[.06] p-8 text-paper/55 sm:col-span-3"><p class="text-[10px] uppercase tracking-[0.18em]">No assets yet</p><p class="mt-3 font-display text-2xl text-paper">Give this idea a face.</p></div>
                        @endforelse
                        @if ($campaign->images->count() < 5)
                            <div class="rounded-[1.35rem] bg-paper/[.04] p-4 ring-1 ring-paper/10 sm:col-span-3">
                                <label class="block text-[10px] font-semibold uppercase tracking-[0.18em] text-paper/45">Add a new asset<input type="file" wire:model="image" accept="image/*" class="mt-3 block w-full text-xs text-paper/60 file:mr-3 file:rounded-full file:border-0 file:bg-gold file:px-4 file:py-2 file:font-semibold file:text-ink file:transition-transform file:duration-700 file:ease-[cubic-bezier(.32,.72,0,1)] hover:file:-translate-y-0.5" /></label>
                                <button type="button" wire:click="uploadImage" wire:loading.attr="disabled" class="mt-4 inline-flex items-center gap-3 rounded-full bg-paper/10 px-4 py-2.5 text-sm font-semibold text-paper transition-all duration-700 ease-[cubic-bezier(.32,.72,0,1)] hover:bg-gold hover:text-ink active:scale-[.98]"><span wire:loading.remove wire:target="uploadImage">Upload asset</span><span wire:loading wire:target="uploadImage">Uploading…</span><span class="flex size-7 items-center justify-center rounded-full bg-paper/10"><svg viewBox="0 0 24 24" fill="none" class="size-3.5" aria-hidden="true"><path d="M12 5v14m-7-7h14" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" /></svg></span></button>
                                <x-input-error for="image" class="mt-2 text-red-300" />
                            </div>
                        @endif
                    </div>
                </div>
            </div>

            <div class="rounded-[2rem] bg-ink/5 p-1.5 ring-1 ring-ink/10" data-animate="fade-up" data-delay="180"><div class="rounded-[calc(2rem-0.375rem)] bg-white/70 p-6 shadow-[0_24px_70px_rgba(71,52,38,.08)] sm:p-8"><p class="text-[10px] font-semibold uppercase tracking-[0.22em] text-moss">Published snapshot</p><div class="mt-6 space-y-5"><div class="flex justify-between gap-4"><span class="text-sm text-ink/50">Campaign status</span><span class="text-sm font-semibold text-moss">{{ $status }}</span></div><div class="h-px bg-ink/10"></div><div class="flex justify-between gap-4"><span class="text-sm text-ink/50">Collecting until</span><span class="text-sm font-semibold">{{ $campaign->end_date->format('d M Y') }}</span></div><div class="flex justify-between gap-4"><span class="text-sm text-ink/50">Start date</span><span class="text-sm font-semibold">{{ $campaign->start_date->format('d M Y') }}</span></div><div class="h-px bg-ink/10"></div><div><p class="text-[10px] uppercase tracking-[0.18em] text-ink/40">Public description</p><p class="mt-3 text-sm leading-6 text-ink/65">{{ $campaign->description }}</p></div></div></div></div>
        </div>

        <div class="mt-16 flex items-end justify-between gap-5 border-b border-ink/10 pb-4" data-animate="fade-up"><div><p class="text-[10px] font-semibold uppercase tracking-[0.22em] text-moss">Edit the source</p><h2 class="mt-2 font-display text-3xl font-semibold tracking-[-0.05em]">Campaign details</h2></div><span class="hidden text-xs text-ink/45 sm:block">Changes save to the live page</span></div>

        <form wire:submit.prevent="editCampaign" enctype="multipart/form-data" class="mt-5 grid gap-5 lg:grid-cols-[minmax(0,1.1fr)_minmax(20rem,.9fr)] lg:gap-8" data-animate="fade-up" data-delay="120">
            @csrf
            <div class="rounded-[2rem] bg-ink/5 p-1.5 ring-1 ring-ink/10"><div class="rounded-[calc(2rem-0.375rem)] bg-white/70 p-6 shadow-[0_22px_65px_rgba(71,52,38,.07)] sm:p-8"><p class="text-[10px] font-semibold uppercase tracking-[0.22em] text-moss">Story</p><div class="mt-7 space-y-6"><label class="block"><span class="text-[10px] font-semibold uppercase tracking-[0.18em] text-ink/45">Title</span><input type="text" value="{{ $title }}" disabled class="mt-2 block w-full rounded-xl bg-ink/5 px-4 py-3 text-sm text-ink/50 ring-1 ring-ink/10" /></label><label class="block"><span class="text-[10px] font-semibold uppercase tracking-[0.18em] text-ink/45">Short description</span><textarea wire:model="description" rows="4" class="mt-2 block w-full resize-y rounded-[1.25rem] bg-paper/70 px-4 py-3 text-sm leading-6 text-ink ring-1 ring-ink/10 outline-none focus:ring-2 focus:ring-accent/40"></textarea><x-input-error for="description" class="mt-2 text-red-500" /></label><label class="block"><span class="text-[10px] font-semibold uppercase tracking-[0.18em] text-ink/45">Full details</span><textarea wire:model="details" rows="8" class="mt-2 block w-full resize-y rounded-[1.25rem] bg-paper/70 px-4 py-3 text-sm leading-6 text-ink ring-1 ring-ink/10 outline-none focus:ring-2 focus:ring-accent/40"></textarea><x-input-error for="details" class="mt-2 text-red-500" /></label></div></div></div>

            <div class="space-y-5">
                <div class="rounded-[2rem] bg-ink/5 p-1.5 ring-1 ring-ink/10"><div class="rounded-[calc(2rem-0.375rem)] bg-white/70 p-6 shadow-[0_22px_65px_rgba(71,52,38,.07)] sm:p-8"><p class="text-[10px] font-semibold uppercase tracking-[0.22em] text-moss">Commercials</p><div class="mt-7 grid gap-4 sm:grid-cols-3 lg:grid-cols-1 xl:grid-cols-3"><label class="block"><span class="text-[10px] uppercase tracking-[0.16em] text-ink/40">Price</span><input type="text" value="{{ $price }}" disabled class="mt-2 block w-full rounded-xl bg-ink/5 px-3 py-2.5 text-sm text-ink/50 ring-1 ring-ink/10" /></label><label class="block"><span class="text-[10px] uppercase tracking-[0.16em] text-ink/40">Starts</span><input type="date" value="{{ $startDate }}" disabled class="mt-2 block w-full rounded-xl bg-ink/5 px-3 py-2.5 text-sm text-ink/50 ring-1 ring-ink/10" /></label><label class="block"><span class="text-[10px] uppercase tracking-[0.16em] text-ink/40">Ends</span><input type="date" value="{{ $endDate }}" disabled class="mt-2 block w-full rounded-xl bg-ink/5 px-3 py-2.5 text-sm text-ink/50 ring-1 ring-ink/10" /></label></div></div></div>

                <div class="rounded-[2rem] bg-ink/5 p-1.5 ring-1 ring-ink/10"><div class="rounded-[calc(2rem-0.375rem)] bg-[#171412] p-6 text-paper shadow-[0_22px_65px_rgba(46,26,71,.12)] sm:p-8" x-data="{ nav: @js($shippingEnabled ? 2 : 1) }"><p class="text-[10px] font-semibold uppercase tracking-[0.22em] text-paper/45">Fulfilment</p><div class="mt-6 flex rounded-full bg-paper/[.06] p-1 ring-1 ring-paper/10"><button type="button" x-on:click="nav = 1" wire:click="resetShipping" x-bind:class="nav == 1 ? 'bg-gold text-ink' : 'text-paper/55 hover:text-paper'" class="flex-1 rounded-full px-3 py-2 text-xs font-semibold transition-all duration-700 ease-[cubic-bezier(.32,.72,0,1)]">Free shipping</button><button type="button" x-on:click="nav = 2" x-bind:class="nav == 2 ? 'bg-gold text-ink' : 'text-paper/55 hover:text-paper'" class="flex-1 rounded-full px-3 py-2 text-xs font-semibold transition-all duration-700 ease-[cubic-bezier(.32,.72,0,1)]">Set rates</button></div><div x-cloak x-show="nav == 2" x-transition class="mt-6 grid gap-4 sm:grid-cols-3"><label class="block"><span class="text-[10px] uppercase tracking-[0.16em] text-paper/40">West Malaysia</span><input type="text" wire:model="shipping.west_malaysia" class="mt-2 block w-full rounded-xl bg-paper/[.06] px-3 py-2.5 text-sm text-paper ring-1 ring-paper/10 outline-none focus:ring-2 focus:ring-gold" /><x-input-error for="shipping.west_malaysia" class="mt-2 text-red-300" /></label><label class="block"><span class="text-[10px] uppercase tracking-[0.16em] text-paper/40">Sarawak</span><input type="text" wire:model="shipping.sarawak" class="mt-2 block w-full rounded-xl bg-paper/[.06] px-3 py-2.5 text-sm text-paper ring-1 ring-paper/10 outline-none focus:ring-2 focus:ring-gold" /><x-input-error for="shipping.sarawak" class="mt-2 text-red-300" /></label><label class="block"><span class="text-[10px] uppercase tracking-[0.16em] text-paper/40">Sabah</span><input type="text" wire:model="shipping.sabah" class="mt-2 block w-full rounded-xl bg-paper/[.06] px-3 py-2.5 text-sm text-paper ring-1 ring-paper/10 outline-none focus:ring-2 focus:ring-gold" /><x-input-error for="shipping.sabah" class="mt-2 text-red-300" /></label></div></div></div>

                <div class="rounded-[2rem] bg-ink/5 p-1.5 ring-1 ring-ink/10"><div class="rounded-[calc(2rem-0.375rem)] bg-white/70 p-6 shadow-[0_22px_65px_rgba(71,52,38,.07)] sm:p-8" x-data="{ variations: @entangle('variations') }"><div class="flex items-end justify-between gap-4"><div><p class="text-[10px] font-semibold uppercase tracking-[0.22em] text-moss">Product options</p><p class="mt-2 text-sm text-ink/50">Name the choices customers can select.</p></div><button type="button" @click="variations.push({name: '', values: ''})" class="flex size-8 items-center justify-center rounded-full bg-ink text-paper transition-transform duration-700 ease-[cubic-bezier(.32,.72,0,1)] hover:-translate-y-0.5 hover:bg-accent"><svg viewBox="0 0 24 24" fill="none" class="size-4" aria-hidden="true"><path d="M12 5v14m-7-7h14" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" /></svg></button></div><div class="mt-6 space-y-3"><template x-for="(variation, index) in variations" :key="index"><div class="grid grid-cols-[.8fr_1.2fr_auto] gap-2"><input type="text" x-model="variations[index].name" placeholder="Option name" class="min-w-0 rounded-xl bg-paper/70 px-3 py-2.5 text-sm text-ink ring-1 ring-ink/10 outline-none focus:ring-2 focus:ring-accent/40" /><input type="text" x-model="variations[index].values" placeholder="Standard, Limited" class="min-w-0 rounded-xl bg-paper/70 px-3 py-2.5 text-sm text-ink ring-1 ring-ink/10 outline-none focus:ring-2 focus:ring-accent/40" /><button type="button" @click="variations.splice(index, 1)" class="flex size-10 items-center justify-center rounded-xl text-ink/40 transition-colors duration-700 ease-[cubic-bezier(.32,.72,0,1)] hover:bg-accent/10 hover:text-accent" aria-label="Remove variation"><svg viewBox="0 0 24 24" fill="none" class="size-4" aria-hidden="true"><path d="m7 7 10 10M17 7 7 17" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" /></svg></button></div></template></div></div></div>
            </div>

            <div class="flex flex-wrap items-center gap-3 lg:col-span-2"><button type="submit" class="group inline-flex items-center gap-4 rounded-full bg-ink px-5 py-3 text-sm font-semibold text-paper transition-all duration-700 ease-[cubic-bezier(.32,.72,0,1)] hover:-translate-y-0.5 hover:bg-accent active:scale-[.98]" wire:loading.attr="disabled"><span wire:loading.remove wire:target="editCampaign">Save changes</span><span wire:loading wire:target="editCampaign">Saving…</span><span class="flex size-8 items-center justify-center rounded-full bg-paper/10 transition-transform duration-700 ease-[cubic-bezier(.32,.72,0,1)] group-hover:translate-x-1"><svg viewBox="0 0 24 24" fill="none" class="size-4" aria-hidden="true"><path d="m5 12 4 4L19 6" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" /></svg></span></button><button type="button" wire:click="$toggle('questionModal')" class="inline-flex items-center gap-3 rounded-full bg-moss/10 px-4 py-3 text-sm font-semibold text-moss ring-1 ring-moss/15 transition-all duration-700 ease-[cubic-bezier(.32,.72,0,1)] hover:-translate-y-0.5 hover:bg-moss hover:text-white"><svg viewBox="0 0 24 24" fill="none" class="size-4" aria-hidden="true"><path d="M9.5 9a2.5 2.5 0 1 1 4.25 1.79c-.85.85-1.75 1.21-1.75 2.46M12 17h.01" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" /><circle cx="12" cy="12" r="8.5" stroke="currentColor" stroke-width="1.4" /></svg>Questions <span class="rounded-full bg-white/70 px-2 py-0.5 text-xs">{{ $campaign->questions->count() }}</span></button><button type="button" wire:click="$toggle('couponModal')" class="inline-flex items-center gap-3 rounded-full bg-gold/15 px-4 py-3 text-sm font-semibold text-deep-gold ring-1 ring-gold/20 transition-all duration-700 ease-[cubic-bezier(.32,.72,0,1)] hover:-translate-y-0.5 hover:bg-gold"><svg viewBox="0 0 24 24" fill="none" class="size-4" aria-hidden="true"><path d="M7 7h10v10H7zM9 12h6" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" /></svg>{{ $campaign->coupon ? 'View coupon' : 'Create coupon' }}</button>@if ($campaign->orders->count() == 0)<button type="button" wire:click="$toggle('deleteCampaignModal')" class="ml-auto inline-flex items-center gap-3 rounded-full px-4 py-3 text-sm font-semibold text-accent ring-1 ring-accent/20 transition-all duration-700 ease-[cubic-bezier(.32,.72,0,1)] hover:bg-accent hover:text-white"><svg viewBox="0 0 24 24" fill="none" class="size-4" aria-hidden="true"><path d="M7 7h10m-8 0v10m6-10v10M9 7V5h6v2m-9 0h12" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" /></svg>Delete campaign</button>@endif</div>
        </form>
    </div>

    <x-dialog-modal wire:model="questionModal">
        <x-slot name="title">Questions ({{ $campaign->questions->count() }})</x-slot>
        <x-slot name="content">
            @if ($campaign->questions->count() == 0)
                <p class="py-8 text-center text-ink/55">No questions have been received for this campaign.</p>
            @else
                <div class="space-y-4">@foreach ($campaign->questions as $question)<article x-data="{ id: '' }" class="rounded-2xl bg-paper p-4 ring-1 ring-ink/10"><p class="text-xs text-moss">Posted {{ $carbon::parse($question->created_at)->format('d M Y, g:i A') }}</p><p class="mt-2 text-ink/80">{{ $question->question }}</p>@if (!$question->reply)<button type="button" x-on:click="id = '{{ $question->id }}'" class="mt-4 text-sm font-semibold text-accent hover:underline">Reply</button><form x-cloak wire:submit.prevent="answer({{ $question->id }})" x-show="id == '{{ $question->id }}'" x-transition class="mt-3"><textarea wire:model="reply" rows="3" class="block w-full rounded-xl bg-white px-3 py-2 text-sm ring-1 ring-ink/10"></textarea><x-input-error for="reply" /><button type="submit" class="mt-2 rounded-full bg-ink px-4 py-2 text-xs font-semibold text-paper">Submit reply</button></form>@else<div class="mt-3 rounded-xl bg-moss/10 p-3"><p class="text-xs text-moss">Replied {{ $carbon::parse($question->reply->created_at)->format('d M Y, g:i A') }}</p><p class="mt-1 text-sm text-ink/70">{{ $question->reply->reply }}</p><button type="button" wire:click="deleteReply({{ $question->reply->id }})" class="mt-2 text-xs font-semibold text-accent hover:underline">Remove reply</button></div>@endif</article>@endforeach</div>
            @endif
        </x-slot>
    </x-dialog-modal>

    <x-dialog-modal wire:model="couponModal" maxWidth="md">
        <x-slot name="title">{{ $campaign->coupon ? 'Coupon code' : 'Create a coupon' }}</x-slot>
        <x-slot name="content">
            @if (!$campaign->coupon)
                <form wire:submit.prevent="generateCoupon" class="space-y-4">@csrf<label class="block text-sm">Code<div class="mt-1 flex gap-2"><input type="text" wire:model="code" disabled class="block min-w-0 flex-1 rounded-xl bg-paper px-3 py-2 uppercase ring-1 ring-ink/10"><button type="button" wire:click="generateCode" class="rounded-full bg-ink px-4 py-2 text-xs font-semibold text-paper">Generate</button></div></label><x-input-error for="code" /><label class="block text-sm">Discount<input type="text" wire:model="discount" class="mt-1 block w-full rounded-xl bg-paper px-3 py-2 ring-1 ring-ink/10"></label><x-input-error for="discount" /><div class="grid grid-cols-2 gap-3"><label class="block text-sm">Limit<input type="text" wire:model="limit" class="mt-1 block w-full rounded-xl bg-paper px-3 py-2 ring-1 ring-ink/10"></label><label class="block text-sm">Expiry<input type="date" wire:model="expiry" min="{{ date('Y-m-d') }}" class="mt-1 block w-full rounded-xl bg-paper px-3 py-2 ring-1 ring-ink/10"></label></div><button type="submit" class="rounded-full bg-ink px-5 py-2.5 text-sm font-semibold text-paper">Save coupon</button></form>
            @else
                <div class="space-y-3 rounded-2xl bg-paper p-5"><p class="font-mono text-2xl font-semibold uppercase tracking-[0.15em] text-accent">{{ $campaign->coupon->code }}</p><p class="text-sm text-ink/65">{{ $campaign->currency }}{{ $campaign->coupon->discount }} off · {{ $campaign->coupon->usage }}/{{ $campaign->coupon->limit }} used</p><p class="text-sm text-ink/55">Valid until {{ $carbon::parse($campaign->coupon->expiry)->format('d F Y') }}</p><x-danger-button wire:click="deleteCoupon({{ $campaign->coupon->id }})">Delete coupon</x-danger-button></div>
            @endif
        </x-slot>
    </x-dialog-modal>

    <x-confirmation-modal wire:model="deleteCampaignModal" maxWidth="lg"><x-slot name="title">Delete campaign</x-slot><x-slot name="content">Are you sure you want to delete this campaign?</x-slot><x-slot name="footer"><x-secondary-button wire:click="$toggle('deleteCampaignModal')">Nevermind</x-secondary-button><x-danger-button class="ml-2" wire:click="deleteCampaign({{ $campaign->id }})">Delete campaign</x-danger-button></x-slot></x-confirmation-modal>
    <x-flash />
</section>
